void copyarr(int *&ptr, int *&copy, int count);
void sort(int *&ptr, int count);
void input(int *&ptr, int count);
void output(int *&ptr, int count);
int mini(int *&ptr, int count);
int maxi(int *&ptr, int count);
void copier(int *&ptr, int *&copy, int count);
void del(int *&ptr, int count, int ind);
void insert(int *&ptr, int count, int ind,int inval);
void MatIn(int arr[3][3]);
void MatOut(int arr[3][3]);
void MultiplyMat(int arr[3][3], int ARR[3][3], int ans[3][3]);